Feature/custom blocks
HisteriaMC/HisteriaPack pull request #10
Opened 2023-08-29 20:48 UTC by HARYA301

2023-08-29 20:49 UTC, HARYA301 commented
Maintenant il y a uniquement les blocks déjà dispo sur histeria et avec le changement du terrain.json et des textures

2023-08-30 13:45 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/51192167-bd96-4bd0-8362-9cafa4ef5397)

2023-08-30 13:48 UTC, dadodasyra requested changes
Je pense que le commit des modèles est un fail, ils n'ont rien à faire dans cette PR. Il manque également un nom correct à la PR.

2023-08-30 13:48 UTC, dadodasyra commented on textures/blocks/drawer_side2.png
Nom du fichier ? peut être faire u ntruc plus explicite et qui suit le format habituel de mc ? (cf four/craft table)

2023-08-30 13:48 UTC, dadodasyra commented on textures/blocks/lucky_block.png
J'aimerai bien un lucky block top plus "vierge", comme le lucky block java

2023-08-30 13:48 UTC, dadodasyra commented on textures/blocks/nocturite_plant0.png
Ne suit tjr pas les noms indiqués, (cf com de la PR #8). _stage_x si je me souviens bien, on s'alligne sur le format vanilla (cf nether_wart)

2023-08-30 13:48 UTC, dadodasyra commented on textures/flipbook_textures.json
> +    "flipbook_texture": "textures/blocks/tinsel",
Concerne pas cette PR

2023-08-30 13:56 UTC, HARYA301 commented
Pour le dernier stage de la plante en noc je vais te faire un truc un peu plus propre
Tu me diras ce que tu en penseras

2023-08-30 14:18 UTC, HARYA301 commented
ça c'est quand la plante est au dernier stage (3) ce qui permet de mieux la distinguer et permet aussi d'être différent des models classique vanilla

![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/ef0a4117-61bb-4028-ad31-78f1168f9847)

2023-08-30 14:29 UTC, dadodasyra commented
non pas à ma connaissance

> > > ça c'est quand la plante est au dernier stage (3) ce qui permet de mieux la distinguer et permet aussi d'être différent des models classique vanilla
> > > ![image](https://user-images.githubusercontent.com/57374230/264371996-ef0a4117-61bb-4028-ad31-78f1168f9847.png)
> > 
> > 
> > ça dépasse de 1 block ?
> 
> Oui, ça pose un problème ou pas?

2023-08-30 14:34 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/309d1fe8-bf85-463d-9e7e-fe1a94007f98)

2023-08-30 14:34 UTC, dadodasyra requested changes

2023-08-30 14:34 UTC, dadodasyra commented on models/blocks/nocturite_plant_stage_3.geo.json
> +				"identifier": "geometry.nocturite_plant",
Faut changer l'id non ?
Faudrait essayer IG aussi de faire direct l'implémentation prcq là le fait d'en avoir 1 stage mais pas les autres me fait peur

2023-08-30 14:34 UTC, dadodasyra commented on models/blocks/nocturite_plant.geo.json
Le nom du fichier me gêne un peu puisqu'on en a un ou c'est précisé le nom. Déjà est ce qu'on est sur qu'il en faut vrm un seul pour les le stage 0 et 1 ? c'est pas la meme hauteur donc pas le meme model non ?

2023-08-30 14:34 UTC, dadodasyra commented on textures/blocks/nocturite_plant_stage_1.png
Réduire de 1 chaque stage. On commence à compter par 0

2023-08-30 14:39 UTC, HARYA301 commented on models/blocks/nocturite_plant.geo.json
C'est la même hauteur pour le 0 et 1

2023-08-30 14:43 UTC, HARYA301 commented
> > Comme ça?
> > ![image](https://user-images.githubusercontent.com/57374230/264377127-309d1fe8-bf85-463d-9e7e-fe1a94007f98.png)
> 
> Ok my bad sur java c'est pas comme ça, je voulais dire un truc plat, comme une table de craft/four/ascenceur. Une texture différente par dessus

![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/834fcf0a-7db5-40c3-890e-dae3c4929641)

2023-08-30 15:04 UTC, dadodasyra commented
> > > Comme ça?
> > > ![image](https://user-images.githubusercontent.com/57374230/264377127-309d1fe8-bf85-463d-9e7e-fe1a94007f98.png)
> > 
> > 
> > Ok my bad sur java c'est pas comme ça, je voulais dire un truc plat, comme une table de craft/four/ascenceur. Une texture différente par dessus
> 
> ![image](https://user-images.githubusercontent.com/57374230/264380212-834fcf0a-7db5-40c3-890e-dae3c4929641.png)

mais du coup tu peux garder le fond qu'il y avait avant, https://raw.githubusercontent.com/HisteriaMC/HisteriaPack/da00c2a002967d632b865a627fb043d2e88d1fb2/textures/blocks/lucky_block.png
je me suis mal exprimé mais je voulais juste pas le point d'interrogation sur le haut et bas quoi

2023-08-30 15:06 UTC, HARYA301 commented
> 

Après j'étais pas particulièrement fan du fond que j'avais fait, je trouve de le laisser comme ça rappel le lucky block classique

2023-08-30 15:11 UTC, dadodasyra approved these changes
les textures à voir avec @AilfeLirik et @Ichabodt

2023-08-30 15:26 UTC, HARYA301 commented
> C'est pas mieux puisque tu as la plante au niveau de la tête

Elle est pas hyper grande non plus
Faut voir in-game
Sinon on remet l'ancienne et puis voilà

2023-09-07 06:49 UTC, HARYA301 commented
Changement du model du la plante stage 2 aujourd'hui pour Ailfe

2023-09-08 12:50 UTC, dadodasyra commented
Je vois aucun push, normalement c'est censé être danzs le nom du commit

2023-09-08 14:04 UTC, HARYA301 commented
> Je vois aucun push, normalement c'est censé être danzs le nom du commit

Y en a pas eu du à un changement de dernière minute que je n'ai push hier

Ce week-end devrait être bon

2023-09-08 14:14 UTC, zelytra commented
Ca ne sert a rien de commenter un truc qui vas venir ( et qui en plus n'as pas été fait) surtout que le nom du commit decris déjà ce que tu as fait

2023-09-09 16:17 UTC, HARYA301 commented
@AilfeLirik @Ichabodt SVP

2023-09-11 21:10 UTC, Ichabodt requested changes
En soi les textures fonctionnent, surtout l'histerite et le nocturite block, mais je ne comprends pas l'intérêt de certains changements très proches des modèles originaux ; je pense à l'**elevator** et au **lucky block**.

Pour le reste je suis assez neutre. J'ai noté des possibles changements à apporter, mais c'est à dado et Ailfe de trancher selon ce qu'ils veulent !

2023-09-11 21:53 UTC, HARYA301 commented on textures/blocks/drawer_front.png
Cette texture est immonde et ressemble à rien du tout

2023-09-11 21:54 UTC, HARYA301 commented on textures/blocks/fertilized_dirt.png
Ailfe m'a demandé de faire comme ça 🤷‍♂️

2023-09-11 21:54 UTC, HARYA301 commented on textures/blocks/random_ore.png
C'était déjà le cas bien avant.
Si tu veux je peux toujours effectuer un changement dessus

2023-09-11 22:14 UTC, Ichabodt commented on textures/blocks/random_ore.png
Oui, avant ou maintenant peu importe, le fait est que ce bloc n'est pas logique. À mon sens, un changement pour le rendre cohérent serait bienvenu 👍

2023-09-11 22:19 UTC, Ichabodt commented on textures/blocks/drawer_front.png
Toujours ce tact légendaire... Autant je suis d'accord que la texture ne colle pas à Minecraft (elle est trop lisse notamment), autant elle est loin d'être immonde.
Cela-dit ça n'a pas d'importance puisque je parlais de s'inspirer du côté vif de ses couleurs, non pas de la refaire. Ta texture est trop terne à mon goût. Toutefois on peut s'en contenter. C'est à dado et Ailfe de voir ce qu'ils veulent !

2023-09-11 22:20 UTC, Ichabodt commented on textures/blocks/fertilized_dirt.png
J'imagine qu'on verra avec son retour

2023-09-12 05:08 UTC, HARYA301 commented on textures/blocks/drawer_front.png
Pour toi elle est loin d'être immonde?
Quand c'est sensé être des tiroirs et que tu as une poignée qui est parfois de un pixel puis parfois de deux pixels, c'est incohérent.

De plus les couleurs ne ressemble pas à celle de bois, d'où l'utilisation d'une couleur se rapprochant du oak car le oak est dans le craft.

2023-09-12 17:51 UTC, Ichabodt commented on textures/blocks/drawer_front.png
J'ai demandé à Ailfe et visiblement le craft se fait avec n'importe quelle **bûche** (peut-être pas les plus récentes) ! On a deux cas donc :
- Logique *table de craft* / *bilbio* : tu restes sur l'oak, tu te fous des autres bois
- Logique *chest* / *outils en bois* : tu ne te bases sur aucun bois, tu innoves pour éviter d'en privilégier un seul

2023-09-12 17:53 UTC, HARYA301 commented on textures/blocks/drawer_front.png
Et bah je vais tweak la palette

2023-09-20 10:55 UTC, HARYA301 commented
SVP, je rappelles qu'on a plus trop le temps

2023-09-20 15:41 UTC, HARYA301 commented on textures/blocks/random_ore.png
> Oui, avant ou maintenant peu importe, le fait est que ce bloc n'est pas logique. À mon sens, un changement pour le rendre cohérent serait bienvenu 👍

Ah et vu la TONNE de loot que le minerai a (qui ne sont pas **que** des minerais) je ne vois pas quoi faire mieux

2023-09-20 15:53 UTC, Ichabodt commented on textures/blocks/random_ore.png
Je vais en parler à Ailfe, déjà voir quels sont les loots du bloc, mais pour moi un changement reste nécessaire !!

2023-09-20 15:58 UTC, Ichabodt commented on textures/blocks/drawer_front.png
Je trouve qu'il y a du mieux. Si les autres n'ont rien à redire je ne vais pas te faire faire plus de changements

2023-09-20 16:11 UTC, HARYA301 commented on textures/blocks/drawer_front.png
C'est largement suffisant, je vais pas mettre la palette de la V6.

2023-09-20 16:16 UTC, dadodasyra commented on textures/blocks/drawer_front.png
C'est du forcing là

2023-09-20 16:18 UTC, dadodasyra commented on textures/blocks/drawer_front.png
Nan haragon je parlais a toi

2023-09-20 16:20 UTC, zelytra commented on textures/blocks/drawer_front.png
Arrêter de polluer le GIT la cours de récrée c'est sur le discord

2023-09-23 20:09 UTC, zelytra commented
La PR est invalide car elle comprend des tâches non nécéssaire pour la v6.5 :
- L'élévateur
- Le lucky block
- La plante en nocturite
- Le drawer
Pour que cette PR soit valide, ces textures doivent être suprimmer de cette branche. Si tu souhaite les ajouter dans le pack, je t'invite a ouvrir une PR qui seras de la priorité médium étant que ce ne sont pas des demandes initial du client.

2023-09-23 20:16 UTC, HARYA301 commented
C'est bon, modifs faites

2023-09-23 20:23 UTC, zelytra commented
Je vois toujours les nouvelles images dans les changements

2023-09-23 20:23 UTC, HARYA301 commented
> Je vois toujours les nouvelles images dans les changements

Lesquelles stp?

2023-10-09 20:37 UTC, HARYA301 commented
@zelytra enlève le tag Invalid, je viens d'edit le lucky block

2023-10-09 20:38 UTC, zelytra commented
faut lire...

2023-10-09 20:39 UTC, HARYA301 commented
> faut lire...

Bah quoi? Les textures que j'avais touché ne sont plus dans la PR

2023-10-09 20:40 UTC, zelytra commented
Je t'invite de nouveaux a relire, au prochain message je la repasse en invalide

2023-10-09 20:41 UTC, HARYA301 commented
> Je t'invite de nouveaux a relire, au prochain message je la repasse en invalide

Bah au lieu de me laisser en plan, dis le, ça ira plus vite

2023-10-09 20:42 UTC, zelytra requested changes
Re-passage en invalide, des ajouts de nouvelles issues dans la PR sans message qui ping les issues a été fait. A corriger.

2023-10-09 20:43 UTC, HARYA301 commented
Bon aller demerdez vous avec les blocks, je reste sur les items

2023-10-09 20:46 UTC, HARYA301 commented
Donc tu veux toujours pas cracher le morceau?

2023-10-09 20:54 UTC, HARYA301 commented
> en gros il a pas comprit il pensait que t'avais remis le lucky block @HARYA301, et il estime tjr que rien que le rename du fichier mérite une issue relié à ça, dans une PR différente

oh mais d'accord
MERCI de le dire! Donc je fais quoi? Je garde les noms de cette PR ou je prends les originaux? On avait parler du faite que vous comptiez rename les blocks

2023-10-09 20:57 UTC, zelytra commented
@HARYA301 
1. Le tag invalide à été retirer il y a 2 semaines, il faut LIRE (c'est pas la première PR ou je te demande juste de LIRE ce qu'il y d'écrit sous tes yeux)
2. De plus arrête de demander qu'on t'explique tout h24 sur le git. Si tu ne comprend pas comment fonctionne github tu demande sur le discord là on pollue la PR
3. Pour continuer tu traite des PR des tâches qui ne sont pas listé notamment le lucky block
4. Arrête de prendre les gens de haut quand tu parle et remet toi en question quand on te répète 6 fois la même chose sans que tu prenne la peine de connecter 2 neurone et de réfléchir
Cordialement et en toute amitié (c fo).

2023-10-09 20:58 UTC, HARYA301 commented
> @HARYA301
> 
> 1. Le tag invalide à été retirer il y a 2 semaines, il faut LIRE (c'est pas la première PR ou je te demande juste de LIRE ce qu'il y d'écrit sous tes yeux)
> 2. De plus arrête de demander qu'on t'explique tout h24 sur le git. Si tu ne comprend pas comment fonctionne github tu demande sur le discord là on pollue la PR
> 3. Pour continuer tu traite des PR des tâches qui ne sont pas listé notamment le lucky block
> 4. Arrête de prendre les gens de haut quand tu parle et remet toi en question quand on te répète 6 fois la même chose sans que tu prenne la peine de connecter 2 neurone et de réfléchir
> 
> Cordialement et en toute amitié (c fo).

Y a pas ton putain de lucky block

2023-10-09 21:00 UTC, HARYA301 commented
Du coup je reste sur ma position, démerdez vous entre vous pour les blocks, c'est plus mon problème :)

2023-10-09 21:00 UTC, zelytra commented
[b6adbe1](https://github.com/HisteriaMC/HisteriaPack/pull/10/commits/b6adbe12d292e834c1f56d37913612c48e32369e) (ceci est un ping github comme tu en utilise peut)

Ce commit touche le lucky block. Une nouvelle fois c'est sous tes yeux

2023-10-09 21:01 UTC, HARYA301 commented
> [b6adbe1](https://github.com/HisteriaMC/HisteriaPack/pull/10/commits/b6adbe12d292e834c1f56d37913612c48e32369e) (ceci est un ping github comme tu en utilise peut)
> 
> Ce commit touche le lucky block. Une nouvelle fois c'est sous tes yeux

MAIS
C'est NORMAL! C'est un rename d'un bloc bordel, la texture n'a pas été changé. Ouvre tes yeux et tu verras que c'est la même que l'ancienne

2023-10-09 21:01 UTC, dadodasyra commented
> Y a pas ton putain de lucky block

En l'occurrence il n'y a pas de PR pour le lucky block, même pour le rename, bien qu'il devrait y en avoir une. Dans les faits actuels il n'y en a pas pour l'instant, et la PR s'occupe déjà de pas mal de chose. Donc il ne devrait y avoir aucun commit relié au lucky bnlock

2023-10-09 21:02 UTC, HARYA301 commented
> > Y a pas ton putain de lucky block
> 
> En l'occurrence il n'y a pas de PR pour le lucky block, même pour le rename, bien qu'il devrait y en avoir une. Dans les faits actuels il n'y en a pas pour l'instant, et la PR s'occupe déjà de pas mal de chose. Donc il ne devrait y avoir aucun commit relié au lucky bnlock

Bon et bien je le rename en sponge

2023-10-09 21:03 UTC, HARYA301 commented
voilà, maintenant c'est bon?

2023-10-09 21:04 UTC, dadodasyra commented
> voilà, maintenant c'est bon?

tant que tu lui dis pas que le neon block n'est pas dedans non plus et qu'il le voit pas ça devrait aller.

2023-10-09 21:06 UTC, HARYA301 commented
> > voilà, maintenant c'est bon?
> 
> tant que tu lui dis pas que le neon block n'est pas dedans non plus et qu'il le voit pas ça devrait aller.

Après le neon est présent depuis un bail et j'ai vu 0 issue dessus donc je n'y touche pas

2023-10-09 21:07 UTC, dadodasyra commented
En l'occurrence tu l'as rename c'est pour ça que je l'ai dit mais on a rien vu chill

2023-10-09 21:08 UTC, HARYA301 commented
> En l'occurrence tu l'as rename c'est pour ça que je l'ai dit mais on a rien vu chill

Ah, ouais bon là j'avoue que j'ai copié de mon fichier à sur la PR, je rename back

2023-10-09 21:09 UTC, zelytra commented
c'est dado qui mergerais cette PR. Je ne prend pas charge de tout ce que cette PR apporte 
![](https://media.tenor.com/4NNFRfah_3cAAAAC/bye-slide.gif)

2023-10-10 17:25 UTC, AilfeLirik approved these changes

2023-10-11 16:40 UTC, Ichabodt commented
Je croyais que tu t'en occupais plus de cette Pr @zelytra 
En plus elle a pas bougé celle-là !
![image](https://github.com/HisteriaMC/HisteriaPack/assets/76227779/bbdd578b-2aee-4c57-b94b-2e5a5289736b)

2023-10-11 16:41 UTC, zelytra commented
Je la refuse, mais a partir du moment ou vous 3 accepter je ne prendrais pas en charge les problème quel causeras et je ma mergerais quand même

2023-10-11 16:43 UTC, Ichabodt commented
Ça explique pas pourquoi tu m'as ping pour review quelque chose que j'ai déjà review

2023-10-11 16:44 UTC, zelytra commented
Ailfe a approuver ile ne reste que toi en terme de retour. Haragon t'as répondu a tout tes messages donc il faut update ta review

2023-10-11 17:08 UTC, Ichabodt approved these changes

2023-10-11 17:11 UTC, merged