Ailfechanges
HisteriaMC/HisteriaPack pull request #100
Opened 2023-10-13 21:42 UTC by AilfeLirik

accept or ban

2023-10-16 07:44 UTC, zelytra requested changes

2023-10-16 07:44 UTC, zelytra commented on particles/blood_particle.json
> +        "linear_acceleration": [ 0, -9.8, 0 ],//earth's acceleration rate
dans du json les commentaire n'existe pas

2023-10-16 07:45 UTC, dadodasyra commented on particles/blood_particle.json
> +        "linear_acceleration": [ 0, -9.8, 0 ],//earth's acceleration rate
Avec l'interpreter vanilla ça fonctionne je crois. J'en ai déjà vu autre part dans des packs

2023-10-16 07:47 UTC, zelytra commented on particles/blood_particle.json
> +        "linear_acceleration": [ 0, -9.8, 0 ],//earth's acceleration rate
Si pour toi c'est bon et que tu me donne ton aval je resolve et approve

2023-10-16 19:28 UTC, dadodasyra commented on particles/blood_particle.json
> +        "linear_acceleration": [ 0, -9.8, 0 ],//earth's acceleration rate
![image](https://github.com/HisteriaMC/HisteriaPack/assets/44753923/2afd1dc1-dd52-4877-9dee-6fbd3049d7c1)
ouep confirmé par https://bugs.mojang.com/browse/MCPE-139618, work as intended

2023-10-16 19:29 UTC, dadodasyra approved these changes

2023-10-17 07:19 UTC, zelytra approved these changes

2023-10-17 07:19 UTC, merged