Nocturite Plant
HisteriaMC/HisteriaPack pull request #110
Opened 2023-10-18 15:29 UTC by HARYA301

2023-10-18 15:29 UTC, HARYA301 commented
#96

2023-10-18 17:09 UTC, dadodasyra requested changes

2023-10-20 08:21 UTC, dadodasyra approved these changes
à tester in game, mais ça a l'air good

2023-10-20 16:20 UTC, Ichabodt reviewed
Yep, un petit visuel du rendu in game pourrait être nice, autrement je pense que ça va !

2023-10-21 08:48 UTC, dadodasyra commented
après beaucoup de test et de sueur: il faut dupliquer le stage 1 et en stage 2, et changer le stage 2 en stage 3, prcq y a 4 étapes de pousse et coté code c'est un enfer à implémenter autrement

2023-10-21 09:34 UTC, HARYA301 commented
Comme ça?
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/ca020d2a-3f85-4493-9fc7-8ff208fc9fdc)

2023-10-21 09:37 UTC, dadodasyra commented
> Comme ça? ![image](https://user-images.githubusercontent.com/57374230/277100089-ca020d2a-3f85-4493-9fc7-8ff208fc9fdc.png)

oui

2023-10-21 09:39 UTC, HARYA301 commented
Je te fais quand même une texture différente pour le stage 2 ou pas du tout?

2023-10-21 09:41 UTC, HARYA301 commented
@Ichabodt 
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/925cb211-b645-48de-b12d-ab3a4fd16afb)

2023-10-21 09:56 UTC, dadodasyra commented
> Je te fais quand même une texture différente pour le stage 2 ou pas du tout?

bah stv

2023-10-21 09:59 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/ec8a1e0a-691b-4467-ba6a-0264078dbad4)

2023-10-21 10:30 UTC, Zeleph1111 approved these changes

2023-10-21 10:32 UTC, dadodasyra commented
@zelytra merge

2023-10-21 13:30 UTC, merged

2023-10-21 16:59 UTC, zelytra commented
Dado sac a merde