item (vague 5)
HisteriaMC/HisteriaPack pull request #111
Opened 2023-10-18 16:13 UTC by HARYA301

#39 #41

2023-10-18 17:00 UTC, AilfeLirik commented
C'est bon pour moi

2023-10-18 17:00 UTC, AilfeLirik approved these changes

2023-10-18 17:10 UTC, dadodasyra approved these changes

2023-10-18 17:12 UTC, Ichabodt requested changes

2023-10-18 17:12 UTC, Ichabodt commented on textures/items/jump_stick.png
Zel : On reprend Edward en vert !
Moi : Osef

2023-10-18 17:12 UTC, Ichabodt commented on textures/items/speed_stick.png
J'ai l'impression de voir une arme blanche médiévale

2023-10-21 13:33 UTC, AilfeLirik approved these changes

2023-10-21 13:41 UTC, HARYA301 commented on textures/items/speed_stick.png
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/f5092005-a0d8-4f7d-b27b-95d2dac6f2ba)

2023-10-21 13:52 UTC, HARYA301 commented on textures/items/jump_stick.png
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/ce3c820a-3c79-47b9-b34f-7ef14028fa40)

2023-10-21 14:21 UTC, HARYA301 commented
@Ichabodt Vite stp

2023-10-21 14:22 UTC, dadodasyra commented
low priority

2023-10-21 14:25 UTC, dadodasyra approved these changes

2023-10-21 14:28 UTC, merged