Changement Post V6.5 (Vague 1)
HisteriaMC/HisteriaPack pull request #139
Opened 2023-10-26 20:17 UTC by HARYA301

#137 #134 #135

2023-10-26 20:19 UTC, dadodasyra requested changes
persuadé qu'il faut histeria:

2023-10-28 12:11 UTC, HARYA301 commented
@dadodasyra C'est bon, j'ai mis histeria:

2023-11-05 18:14 UTC, dadodasyra commented
pas en merge sur la bonne branch je pense

2023-11-05 19:00 UTC, HARYA301 commented
> pas en merge sur la bonne branch je pense

Je te mets ça sur main

2023-11-06 09:30 UTC, dadodasyra reviewed
Les coeurs m'ont l'air dégueulasse, moyen de voir un rendu ig

2023-11-06 10:22 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/f31d9a8e-a600-4a4d-a333-821011ddf697)

2023-11-06 10:23 UTC, HARYA301 commented
C'est le screen du fix de la dyna mais y a les cœurs infâme

2023-11-06 22:32 UTC, dadodasyra commented
Pourquoi copier les vanilla.. mais euh les changer.. fin jsp autant laisser les vanilla

2023-11-17 16:42 UTC, dadodasyra commented
Pour moi faut laisser les coeurs vanilla

2023-12-01 18:23 UTC, HARYA301 commented
> Pour moi faut laisser les coeurs vanilla

c'est fait

2023-12-01 19:03 UTC, dadodasyra approved these changes

2023-12-03 19:29 UTC, merged