Items Boss
HisteriaMC/HisteriaPack pull request #145
Opened 2023-10-28 13:57 UTC by HARYA301

#142 #143 #141 #140

2023-10-29 17:23 UTC, HARYA301 commented
@AilfeLirik

2023-10-30 22:46 UTC, AilfeLirik commented
Ok alors, le caducée c'est bien

2023-10-30 22:47 UTC, AilfeLirik commented
Le philtre pour moi c'est trop gros, je vois bien un petite fiole rose pour l'amour mais genre rose pink

2023-10-30 22:47 UTC, AilfeLirik commented
Pour la torche je suis pas convaincu non plus, essaie de faire une forme un peu atypique (courbée + forme dague sur le bout) avec des flammes de la couleur de son voile

2023-10-30 22:48 UTC, AilfeLirik commented
Pour le sort met la fleur de lotus au centre

2023-10-30 23:00 UTC, HARYA301 commented
et maintenant?

2023-11-06 08:25 UTC, zelytra commented
PR pour v6.5.1 ?

2023-11-06 09:10 UTC, dadodasyra commented
Oui

2023-11-06 09:33 UTC, dadodasyra approved these changes
C'est à Ailfe d'approuver ça, pas moi

2023-11-17 14:40 UTC, zelytra commented
@AilfeLirik faut se réveiller

2023-12-01 17:53 UTC, HARYA301 commented
Ailfe... Tu comptes en faire quelque chose de la PR ou?

2023-12-01 18:00 UTC, AilfeLirik commented
Si tu sais me les envoyer en gros je suis incapable de zoomer

2023-12-01 18:14 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/ba6ebac6-c08b-486c-a8f1-0abe13d4a025)

2023-12-01 18:20 UTC, AilfeLirik commented
la torche je parlais de courber le manche

2023-12-01 18:21 UTC, AilfeLirik commented
nop

2023-12-01 18:21 UTC, HARYA301 commented
Fais moi un dessin je comprends rien

2023-12-01 19:05 UTC, dadodasyra requested changes

2023-12-01 19:05 UTC, dadodasyra commented on textures/item_texture.json
> +      "textures": "textures/items/utility/love_philtre"
problème de merge là, t'as overwrite un truc déjà merge nan ?

2023-12-01 19:06 UTC, HARYA301 commented on textures/item_texture.json
> +      "textures": "textures/items/utility/love_philtre"
Bah j'ai enlevé les trucs des bonbons car inutiles et aussi PR approuvé trop tard

2023-12-03 00:46 UTC, dadodasyra commented on textures/item_texture.json
> +      "textures": "textures/items/utility/love_philtre"
Mais supprimer tout c'est pas résoudre un conflit mec

2023-12-03 00:50 UTC, HARYA301 commented
je reverte le json item demain

2023-12-03 19:24 UTC, HARYA301 commented
json modifié

2023-12-03 19:25 UTC, dadodasyra approved these changes
@AilfeLirik confirmation

2023-12-03 19:25 UTC, HARYA301 commented
Ailfe, fais moi un dessin de ce que tu me veux pour la torche

2023-12-03 20:04 UTC, AilfeLirik commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/95536716/6afc93e5-ee97-4585-aeda-c03c69327584)

2023-12-03 20:18 UTC, HARYA301 commented
ça va rendre mal en 16

2023-12-03 20:20 UTC, AilfeLirik commented
Tu n'es pas obligé de forcer autant la courbure

2023-12-03 20:21 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/74934ac2-bdce-4412-8db9-a6c73f3c9251)

2023-12-03 20:23 UTC, AilfeLirik commented
Le socle autour du feu est trop fat et ducoup le manche est trop petite ce qu'il t'empêche de la courber propre

2023-12-03 20:23 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/f0c914ee-e381-4750-9d73-fcb21fe1b96d)

2023-12-03 20:23 UTC, AilfeLirik commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/95536716/48eab69f-1050-4fc3-949c-0080c5b490a3)

2023-12-03 20:26 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/b77e4831-ce90-4fe8-a473-2102ec879bdb)

2023-12-17 14:29 UTC, dadodasyra commented
As always no news @AilfeLirik

2024-02-04 11:11 UTC, dadodasyra commented
@AilfeLirik

2024-03-23 20:05 UTC, HARYA301 commented
et là ?

2024-03-23 23:28 UTC, AilfeLirik commented
Agrandis la flamme sinon c'est bien👍

2024-06-18 12:21 UTC, HARYA301 commented
> Agrandis la flamme sinon c'est bien👍

![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/1c7860c2-09f9-4784-ac8c-f52a723b4851)

2024-06-18 12:35 UTC, AilfeLirik commented
Essaie de moins courber la flamme dans la directe du manche, ça faire trop anglé

2024-06-18 12:41 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/32b55894-e7ec-4568-93b4-eefe5a65bcdc)

2024-06-18 12:47 UTC, AilfeLirik commented
Met vraiment la flâme plus verticale s'il-te-plait, et essaie de mettre du rouge sang en haut de la flamme

2024-06-18 12:51 UTC, HARYA301 commented
et là
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/316210d4-e002-4927-8224-11b959922066)

2024-06-18 12:51 UTC, AilfeLirik commented
Nickel; maintenant change juste la couleur de la flamme pour aller vers du rouge sang

2024-06-18 12:51 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/4d4e3e94-6085-44f7-8f86-cd0beb700836)

2024-06-18 12:52 UTC, HARYA301 commented
elle est bien là couleur? (image du dessus)

2024-06-18 12:53 UTC, AilfeLirik commented
Vasi vraiment trop fort sur le rouge sang hésite pas, ça doit être la couleur dominante dans la flamme

2024-06-18 12:54 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/23c6e1f4-c998-4357-b513-90da7dd3154a)

2024-06-18 12:56 UTC, AilfeLirik commented
Mais tu es timide mdr, En gros on va dire que le rouge entier de la flamme, toute la flamme carrément doit tourner vers le violet en terme de rouge, une couleur entre rouge et violet en gros

2024-06-18 13:03 UTC, HARYA301 commented
t'as vraiment intérêt de me dire que c'est bon

2024-06-18 13:06 UTC, AilfeLirik commented
Parfait

2024-06-18 13:07 UTC, AilfeLirik commented
C'est tout bon

2024-06-18 13:08 UTC, HARYA301 commented
Faut que je fasse les fichiers txt aussi

2024-08-14 11:49 UTC, dadodasyra requested changes
love_philtre ça veut rien dire aussi

2024-08-27 12:00 UTC, HARYA301 commented
@dadodasyra J'ai modifié le nom et corrigé la } manquante

2024-08-28 07:30 UTC, dadodasyra commented
On standby, je veux pas merge et puis on l'oublie, y a aucune implémentation coté code @AilfeLirik

2024-10-17 20:55 UTC, AilfeLirik commented
Les quatres items en question ont été implémentés, il faudrait passer la PR

2024-10-18 19:13 UTC, AilfeLirik commented
Il y a des textures et items à renommer

2024-10-18 19:13 UTC, AilfeLirik commented
![image](https://github.com/user-attachments/assets/942117b7-5a3d-4a16-ad3b-8df3122c0c82)

2024-10-19 16:51 UTC, closed without merging

2024-10-19 16:51 UTC, HARYA301 commented
décalé sur une autre