Bonbons
HisteriaMC/HisteriaPack pull request #146
Opened 2023-10-28 15:47 UTC by HARYA301

#144

2023-10-28 21:56 UTC, ItamSurMc requested changes
La couleur du bâton est trop claire pour le green.

2023-10-28 21:59 UTC, ItamSurMc requested changes
Inverse les couleurs entre le red et le yellow, un sucre d'orge est toujours rouge, pas jaune.

2023-10-28 22:03 UTC, HARYA301 commented
et maintenant?

2023-10-28 22:31 UTC, ItamSurMc reviewed
t'as réellement changé la couleur du bâton du green ?

2023-10-28 22:33 UTC, HARYA301 commented
> t'as réellement changé la couleur du bâton du green ?

Oui et bien

2023-10-29 19:44 UTC, ItamSurMc approved these changes

2023-11-03 21:04 UTC, dadodasyra approved these changes
Je vois pas trop de soucis à ça notamment si Itam est ok

2023-11-27 08:07 UTC, merged