Drawer + upgrade
HisteriaMC/HisteriaPack pull request #177
Opened 2023-12-08 18:21 UTC by HARYA301

#175
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/27ace9fc-fe3f-4aff-9e58-b261785cfe2f)
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/c97b0bfc-4cc0-4229-af13-b261af7bcfa0)
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/e899dd77-120b-434c-9911-84c361c754b4)
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/e033b1b0-6193-4b90-82cf-7abd1f8639e3)
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/6172dea4-b108-48dd-8284-7378fc07d39f)
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/b041e6a6-06c4-4e4f-ab6a-0f9e9eec4575)

2023-12-08 18:26 UTC, SwouitAzia commented
superbe gg

2023-12-09 09:34 UTC, HARYA301 commented
J'ajouterai ça dans blocks.json et terrains.json une fois les textures approuvés

2023-12-13 13:03 UTC, dadodasyra requested changes
Nom des fichiers à match, soit supprimer le 6 tirroirs soit supprimer le 1.
Je reste assez mitigé en général et je pense que ça devrait être merge sur la v7.

2023-12-13 13:03 UTC, dadodasyra commented on textures/blocks/drawer_front6.png
y a 5 upgrade

2023-12-13 13:05 UTC, HARYA301 commented on textures/blocks/drawer_front6.png
Tu es mitigé sur quoi exactement?

2023-12-13 14:04 UTC, dadodasyra commented
> Nom des fichiers à match
= _2 pas pareil que 2

2024-06-18 11:31 UTC, dadodasyra requested changes
Toujours le nom du fichier

2024-06-18 12:02 UTC, HARYA301 commented
Pour que ce soit plus visible le niveau du drawer, why not ajouté une bordure représenté par les minerais MC (comme ça ça permet de voir l'importance du lvl) en plus du devant qui change mais qui de loin ne soit pas trop

2024-06-18 12:06 UTC, AilfeLirik commented
C'est propre, je trouve ça très vanilla ça pourrait limite être dans le jeu de base en fait

2024-06-18 12:07 UTC, AilfeLirik commented
à voir si ça mériterait pas un peu de renforcement des couleurs sur les poignées ou quoi pour sortir du color patern du chest

2024-06-18 13:58 UTC, dadodasyra requested changes
Impossible à tester le [terrain_texture.json](https://github.com/HisteriaMC/HisteriaPack/pull/177/files#diff-ff921eba0ea5fade2f1f06a443b59186fd8df49f52e672fef49e5725d256e831) ne contient pas les fichiers

2024-06-18 13:58 UTC, HARYA301 commented
ça arrive dans la journer

2024-06-20 08:57 UTC, HARYA301 commented
Plutôt aujourd'hui

2024-06-20 09:33 UTC, HARYA301 commented
@dadodasyra Pour le blocks.json, je me démerde comment?

2024-06-20 09:36 UTC, HARYA301 commented
En attendant une réponse j'ai fait ça
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/6ef55976-6129-42f1-9ce1-d73bdc6e45c4)

2024-06-20 09:41 UTC, dadodasyra commented
Comme les lamp

2024-06-20 09:42 UTC, HARYA301 commented
Ouais donc comme j'ai fait quoi

2024-06-20 21:18 UTC, dadodasyra approved these changes

2024-06-20 21:19 UTC, merged