blocks.json / Texts / Texture entity
HisteriaMC/HisteriaPack pull request #183
Opened 2023-12-13 13:19 UTC by SwouitAzia

2023-12-13 13:41 UTC, dadodasyra requested changes
+Fix en anglais

2023-12-13 13:41 UTC, dadodasyra commented on blocks.json
> +        "sound": "metal",
testé? ça existe ?

2023-12-13 13:41 UTC, dadodasyra commented on texts/fr_FR.lang
> +[Inventorys]
damn ça veut rien dire ça

2023-12-13 13:41 UTC, dadodasyra commented on texts/fr_FR.lang
>  item.histeria:buy=Acheter
donc tu rajoutes des s mais pas ici

2023-12-13 13:41 UTC, dadodasyra commented on textures/entity/grapling_hook.png
c quoi

2023-12-13 13:47 UTC, HARYA301 commented
Il mets les traductions en FR mais le truc c'est qu'in-game les noms ne seront pas traduit sans aucune raison

2023-12-13 14:04 UTC, dadodasyra commented
> Il mets les traductions en FR mais le truc c'est qu'in-game les noms ne seront pas traduit sans aucune raison

c'est que c pas la bonne clé alors

2023-12-17 14:21 UTC, dadodasyra commented on texts/fr_FR.lang
> +[Inventorys]
```suggestion
[Inventories]
```

2023-12-17 14:22 UTC, dadodasyra approved these changes

2023-12-17 14:23 UTC, dadodasyra approved these changes

2023-12-17 14:23 UTC, HARYA301 commented on blocks.json
> +        "sound": "metal",
ça n'a aucun sens parce que tout les minerais quand ils sont cassé font le bruit de la stone, pas d'un block de fer ou diamant

2023-12-17 14:23 UTC, merged