Event Paques
HisteriaMC/HisteriaPack pull request #199
Opened 2024-03-28 23:49 UTC by SwouitAzia

**Models :**
- oeuf chocolat bombe
- oeuf chocolat bloc
- sceptre chocolat

**Textures items :**
- oeuf chocolat
- lapin chocolat
- oeuf or
- tablette chocolat
- panier oeufs
- sceptre chocolat

+ fichiers texts mis à jour.
![sceptre choco](https://github.com/HisteriaMC/HisteriaPack/assets/126331308/2df8904c-1263-44f5-8414-d375ff2d232a)
![chocolate_egg_blockpreview](https://github.com/HisteriaMC/HisteriaPack/assets/126331308/077f642c-9f8a-4b27-b362-0cf072ec8203)
![chocolate_egg_bomb](https://github.com/HisteriaMC/HisteriaPack/assets/126331308/2062a045-a7f7-4c6d-bf1a-b74c1654436c)

2024-03-29 09:14 UTC, Tonmou8128 commented
Les models sont vraiment bien travaillés, moi je ne vois rien à redire

2024-03-29 14:45 UTC, dadodasyra commented
@HARYA301 review, avant ce soir

2024-03-29 15:13 UTC, HARYA301 commented
Bien

2024-03-29 15:21 UTC, dadodasyra requested changes

2024-03-29 15:21 UTC, dadodasyra commented on entity/chocolate_egg_bomb
extension de fichier

2024-03-30 10:00 UTC, dadodasyra approved these changes

2024-03-30 10:00 UTC, merged