Items et fichiers json
HisteriaMC/HisteriaPack pull request #22
Opened 2023-09-23 14:46 UTC by HARYA301

2023-09-23 14:47 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/634417b2-fc5c-4211-a7f3-995f307fd0d0)

2023-09-23 14:47 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/fc4c0703-a7b1-463d-b806-7510f545fbb1)

2023-09-23 20:21 UTC, HARYA301 commented
Je vais push la clé et le calice ici, j'ai par la même occasion rename la PR pour cette effet.

2023-09-23 20:37 UTC, HARYA301 commented
Le calice de dionysos pushé

2023-09-25 16:59 UTC, AilfeLirik commented
Le calice doit être en or avec un peu d'hist mais il doit être en or

2023-09-25 17:07 UTC, HARYA301 commented
> Le calice doit être en or avec un peu d'hist mais il doit être en or

c'est bon

2023-09-25 17:53 UTC, zelytra commented
Par contre @HARYA301 stop ajouter des choses alors que ta PR est prête a relu, c'est contre productif.
Quand tu ouvre une PR elle censé être carré et prête a être merge, pas a subir des modifications de dernières minute sen ajoutant un truc apr ci par là.

Sinon tu met la PR en mode draft afin de dire aux autre que la PR est ouverte mais que tu travaille toujours dessus.

2023-09-25 17:54 UTC, HARYA301 commented
C'était pas prévu de base, c'est pour ça.
J'ai trouvé que faire une seule PR c'était mieux que plusieurs qui parlent de la même chose

2023-10-02 14:51 UTC, zelytra commented
Ping les issues lier a ce que tu a ajouter quand tu fait ca @HARYA301

2023-10-04 06:39 UTC, dadodasyra approved these changes
Pour ma part ça va, mais ce qui compte c'est @AilfeLirik on this side

2023-10-04 15:21 UTC, AilfeLirik commented
Ok c'est bon

2023-10-04 15:21 UTC, AilfeLirik approved these changes
Tout est bon ici

2023-10-04 15:46 UTC, zelytra commented
Harya c'est cool de mettre un thumbs up sur mon message mais faut le faire. Il y a des tâches en plus faite ici non assigné a la pr

2023-10-04 15:49 UTC, HARYA301 commented
#9 #24 #23 #19

2023-10-04 15:49 UTC, zelytra commented
Non ,car pour la 3eme fois tu n'as toujours pas dit ce que tu a ajouter en plus dans les changement que les issues ne prennent pas en compte. Faut lire les messages

2023-10-04 15:49 UTC, zelytra commented
enfin

2023-10-04 15:50 UTC, HARYA301 commented
#14

2023-10-04 15:52 UTC, zelytra commented
ca n'as aucun sens fais moi un message qui me dit ce que tu a ajouter comme issue. Sans faire 15 messages différans sans aucun sens

2023-10-04 15:53 UTC, HARYA301 commented
> ca n'as aucun sens fais moi un message qui me dit ce que tu a ajouter comme issue. Sans faire 15 messages différans sans aucun sens

Regarde les textures que j'ai ajouté dans la PR et ça ira plus vite que si c'était moi

2023-10-04 15:54 UTC, HARYA301 commented
> Dans ce cas je bloque la PR tant que le message metant a jours les issues n'as pas été fait par le commanditaire de la PR

roh bordel

tu as déjà lié des issues en plus

2023-10-04 15:55 UTC, zelytra requested changes
En attente du listing des tâches exacte qui on été faite ici

2023-10-04 15:56 UTC, HARYA301 commented
> En attente du listing des tâches exacte qui on été faite ici

Tiens, les manquantes:
#14 #12

2023-10-04 15:58 UTC, zelytra commented
Je vois un dionysus_chalice en plus lié a quel issue ?

2023-10-04 15:58 UTC, HARYA301 commented
#26

2023-10-04 16:10 UTC, dadodasyra commented
> @dadodasyra on attend la validation d' @Ichabodt ?

Peut être lui laisser la possibilité ce soir. Sinon merge

2023-10-04 18:16 UTC, Ichabodt requested changes
Dans l'ensemble je trouve ça bien, je ne suis juste pas trop fan de la boss key, mais ce qui m'embête vraiment c'est le calice !

2023-10-04 18:16 UTC, Ichabodt commented on textures/items/dionysus_chalice.png
Je sais que je t'emmerde encore, mais je n'aime vraiment pas cette texture. Essaie déjà de retirer les sortes de cornes. Quant à l'histerite, je sais que c'est une demande d'Ailfe, mais je ne pense pas qu'elle soit nécessaire si elle vient entacher la texture

2023-10-04 18:19 UTC, HARYA301 commented on textures/items/dionysus_chalice.png
OK pour le premier point.
Non pour le deuxième, tu l'as évoqué mais c'est sur demande.

2023-10-04 18:25 UTC, HARYA301 commented on textures/items/dionysus_chalice.png
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/da72daca-ba24-40be-8f77-28e7bf5f6d2b)

2023-10-04 18:26 UTC, AilfeLirik commented on textures/items/dionysus_chalice.png
Je suis d'accord avec icha

2023-10-04 18:34 UTC, Ichabodt commented on textures/items/dionysus_chalice.png
Je le trouve beaucoup mieux simple comme ça. Vois peut-être à mettre l'histerite comme un ornement plutôt plutôt qu'une incrustation qui le traverse de part en part

2023-10-04 19:22 UTC, Ichabodt commented on textures/items/dionysus_chalice.png
Nice, j'aime mieux ! @AilfeLirik ?

2023-10-04 19:35 UTC, AilfeLirik commented on textures/items/dionysus_chalice.png
nickel

2023-10-05 07:13 UTC, zelytra commented
@Ichabodt manque plus que ton avale

2023-10-06 18:11 UTC, HARYA301 commented
vite @Ichabodt

2023-10-06 21:00 UTC, Ichabodt approved these changes

2023-10-06 21:01 UTC, HARYA301 commented
Plus qu'à merge

2023-10-06 21:03 UTC, Ichabodt commented
Pour le merge je laisse faire les autres, je préfère pas faire de conneries. Github c'est pas mon fort

2023-10-06 21:09 UTC, merged