BC 1
HisteriaMC/HisteriaPack pull request #257
Opened 2024-08-19 19:56 UTC by HARYA301

#254 #253 #255 #249 #251 #243 

Look du Vault
![image](https://github.com/user-attachments/assets/6764a731-c7de-4633-93c1-628a75ccf0b5)

2024-08-19 20:10 UTC, AilfeLirik commented
On peut avoir les autres looks ?

2024-08-20 06:58 UTC, dadodasyra requested changes

2024-08-20 06:58 UTC, dadodasyra commented on blocks.json
> +    "duping_tnt" : {
pas de histeria: ?

2024-08-20 06:58 UTC, dadodasyra commented on blocks.json
> +    "iem_tnt" : {
pareil ?

2024-08-20 06:58 UTC, dadodasyra commented on blocks.json
> +    "histerite_tnt" : {
pareil ?

2024-08-20 06:58 UTC, dadodasyra commented on blocks.json
> +    "duping_tnt" : {
sinon c un peu à chier comme non jtrouve

2024-08-20 06:58 UTC, dadodasyra commented on blocks.json
> +    "nocturite_tnt" : {
pareil ?

2024-08-20 21:12 UTC, HARYA301 commented
Je viens de fix les "histeria:" manquant, les render arrivent

2024-08-20 21:14 UTC, HARYA301 commented
Alert block:
![image](https://github.com/user-attachments/assets/7e35a71f-41ca-47b3-be49-5edf5c3b136f)

2024-08-20 21:17 UTC, HARYA301 commented
Noc & Hist Reinforced Obsi
![image](https://github.com/user-attachments/assets/097e3957-7c7e-4dd7-a020-71c61084e582)

2024-08-20 21:22 UTC, HARYA301 commented
Dans l'ordre
Duping TNT, IEM TNT, Noc TNT & Hist TNT
![image](https://github.com/user-attachments/assets/50e98e45-6cf4-4217-89b4-d6aa312c83b2)

2024-08-20 21:24 UTC, HARYA301 commented
Generator On & Off
![image](https://github.com/user-attachments/assets/ac2ca070-7387-449a-bf28-c22117444af8)

2024-08-23 00:40 UTC, HARYA301 commented
Des retours depuis?

2024-08-23 06:39 UTC, dadodasyra requested changes

2024-08-23 11:57 UTC, HARYA301 commented
C'est bon maintenant

2024-08-23 12:22 UTC, dadodasyra commented
aucun commit @HARYA301

2024-08-23 12:28 UTC, HARYA301 commented
oh le con

2024-08-23 12:28 UTC, HARYA301 commented
voilà

2024-08-23 12:39 UTC, dadodasyra approved these changes

2024-08-23 18:07 UTC, AilfeLirik approved these changes

2024-08-23 18:34 UTC, AilfeLirik commented
Pour l'alert block il faut faire un top et un down custom ça rend mal actuellement

2024-08-23 18:36 UTC, AilfeLirik commented
Il faudrait essayer d'ajouter un éclair jaune sur la TNT IEM

2024-08-23 18:48 UTC, HARYA301 commented
> Pour l'alert block il faut faire un top et un down custom ça rend mal actuellement

![image](https://github.com/user-attachments/assets/612e5a8a-11e8-4a2f-a2f0-674eefc47d88)

2024-08-23 18:49 UTC, HARYA301 commented
c'est pas encore commit

2024-08-23 18:51 UTC, AilfeLirik commented
ça fonctionne bien

2024-08-23 19:00 UTC, HARYA301 commented
Sur la dumping j'ai jouté les éclairs là
![image](https://github.com/user-attachments/assets/48fb1494-f060-4d6e-8e82-76f41cd1a9fd)

2024-08-23 19:01 UTC, HARYA301 commented
Sinon pour les alerts blocks c'est bon

2024-08-23 19:50 UTC, HARYA301 commented
Issue de dernière minute, le mixed sand arrive

2024-08-23 20:23 UTC, HARYA301 commented
#244

2024-08-23 20:25 UTC, AilfeLirik commented
L'éclair c'est pour la tnt bleu

2024-08-23 20:25 UTC, HARYA301 commented
putain le con

2024-08-23 20:25 UTC, AilfeLirik commented
le duping au fait il faut faire des changement on dirait trop un tnt de poison/nucléaire

2024-08-23 20:25 UTC, HARYA301 commented
> le duping au fait il faut faire des changement on dirait trop un tnt de poison/nucléaire

une idée ?

2024-08-23 20:26 UTC, AilfeLirik commented
Des flèches de direction

2024-08-23 20:26 UTC, HARYA301 commented
couleur tjrs verte?

2024-08-23 20:31 UTC, HARYA301 commented
Les fleches sont juste pour une indication elles vont pas rester noires
![image](https://github.com/user-attachments/assets/2bb10f20-2936-4139-af5f-768643f11d8a)

2024-08-23 20:34 UTC, HARYA301 commented
![image](https://github.com/user-attachments/assets/c551fb88-a463-4cf6-9cb3-f11bac308a1a)

2024-08-27 06:22 UTC, merged