BC 2
HisteriaMC/HisteriaPack pull request #263
Opened 2024-09-11 18:04 UTC by HARYA301

2024-09-17 16:33 UTC, AilfeLirik commented
Il me faudrait une liste de screen des rendus des changements

2024-09-17 16:35 UTC, HARYA301 commented
Quels changements tu me parles? Les catalysts ainsi que le canon?

2024-09-17 16:53 UTC, AilfeLirik commented
Bah ce que tu changes dans cette pr

2024-09-17 16:54 UTC, HARYA301 commented
okay

2024-09-17 16:55 UTC, HARYA301 commented
En vrai t'abuses un peu tu pourrais check la category "Files changed"

2024-09-19 16:32 UTC, AilfeLirik commented
C'est un enfer et j'ai quasiment aucun temps dans la semaine alors si tu en as plus que moi ça serait gentil ça me ferais gagner du temps

2024-09-21 11:38 UTC, HARYA301 commented
Pied de biche (pour debloquer la coffre fort) et l'item du canon
![image](https://github.com/user-attachments/assets/b627c677-88a4-4929-a628-d55884da2c46)

2024-09-21 11:39 UTC, HARYA301 commented
Levitating Obsidian
![image](https://github.com/user-attachments/assets/8aca1a26-2ed7-473f-8ea5-f140f360aca6)

2024-09-21 11:42 UTC, HARYA301 commented
Le canon
![image](https://github.com/user-attachments/assets/06c6e1dd-72e4-4d9f-aee9-ddcba7afd7e3)

2024-09-21 11:43 UTC, HARYA301 commented
générateur
![image](https://github.com/user-attachments/assets/d6c5f4ea-cd72-41ae-8b51-80fad73f0bb1)

2024-09-21 11:44 UTC, AilfeLirik commented
Pour le pied du canon il fallait laisser en bleu, ce sont les blocks de défense qui sont rouges

2024-09-21 11:45 UTC, HARYA301 commented
Relfector
![image](https://github.com/user-attachments/assets/49a2d924-bfe7-407a-a6f9-415a18efffb7)

2024-09-21 11:53 UTC, HARYA301 commented
Catalyst éteint avec un exemple d'une des couleurs quand il est allumé 
![image](https://github.com/user-attachments/assets/ae6040c0-cf9a-4d2f-bc53-62b78a358e3d)

2024-09-21 12:02 UTC, HARYA301 commented
Des choses à dire sinon? @AilfeLirik

2024-09-21 12:28 UTC, HARYA301 commented
Alert block
![image](https://github.com/user-attachments/assets/cfa59492-a2d2-4f05-965c-47f0fed2a7f7)

2024-09-21 12:47 UTC, AilfeLirik commented
Tu penses qu'il faudrait changer un peu la texture du generator pour l'accorder ?

2024-09-21 12:47 UTC, HARYA301 commented
> Tu penses qu'il faudrait changer un peu la texture du generator pour l'accorder ?

Bah je trouve pas
Peut-être la couleur cependant

2024-09-21 12:53 UTC, AilfeLirik commented
Bah oui la cage est noire, après trouve peut un entre deux ça va mal rendre si tu met encore le même fond

2024-09-21 12:56 UTC, HARYA301 commented
Avant/après
![image](https://github.com/user-attachments/assets/fde6ea17-c5e6-4fe6-9583-c6eaf0a62a78)

2024-09-21 13:03 UTC, AilfeLirik commented
nan mais trouve un mix entre ça et le patern des autre blocks de défense mdr

2024-09-21 13:04 UTC, HARYA301 commented
> nan mais trouve un mix entre ça et le patern des autre blocks de défense mdr

T'es marrant toi. Tu penses à ce que tu veux avoir mais tu me le dis pas mdr
Bref, encore un bloc qui va ressembler à un autre c'est complétement con mais bon hein

2024-09-21 13:12 UTC, AilfeLirik commented
Nan mais oskour c'est pas compliqué ce que je t'explique, 
- Toutes les défenses suivent la même patern
- Le generateur est différent jusqu'ici, mettre ce même patern dessus risque de mal rendre
- C'est pourquoi pour tout de même le faire concorder avec le reste des textures il faut, pour sa texture, faire un mix du noir avec le patern pour obtenir une couleur entre deux qui marquera quand même la différence tout est évitant le Hors-Sujet

2024-09-21 13:15 UTC, HARYA301 commented
Tu crois vraiment que les gens en ont quelques choses à foutre que  ce soit raccord ou pas? Les joueurs n'en ont rien à foutre tant que ça marche et tu le expliques. Tu peux pas foutre un même pattern partout c'est complétement con. Imagine si tous les blocs MC qui avait cette même idée, les blocs se ressembleraient tous
MAIS BON comme tu veux hein, je vais faire comme monsieur à envi hein

2024-09-21 13:22 UTC, HARYA301 commented
![image](https://github.com/user-attachments/assets/aa30b34e-b871-4ed5-a91c-3d62ed8da804)

2024-09-21 13:49 UTC, HARYA301 commented
@AilfeLirik t'en penses quoi pour que je suis passer à autre chose?

2024-09-21 13:55 UTC, AilfeLirik commented
Tu saurais m'en faire une vue 3d pls ?

2024-09-21 13:57 UTC, HARYA301 commented
tiens
![image](https://github.com/user-attachments/assets/be446a10-1e1c-413a-bc39-bbd9c5551305)

2024-09-21 13:58 UTC, AilfeLirik commented
C'est bien mais la bordure est trop marquée, tu abandonne le haut et le bas modifiés aussi ?

2024-09-21 14:04 UTC, HARYA301 commented
et là?
![image](https://github.com/user-attachments/assets/4cf89aaf-c8d6-4b8b-a2f6-d70e2566aeff)

2024-09-21 14:20 UTC, AilfeLirik commented
Ok c'est bien, à voir le rendu en jeu, montre la version éteinte avec pls

2024-09-21 14:21 UTC, HARYA301 commented
version éteinte
![image](https://github.com/user-attachments/assets/1648d94a-19ee-4636-ad0b-8071e48d903a)

2024-09-21 14:22 UTC, AilfeLirik commented
Fonce un tout petit peu le contour clair sur le haut

2024-09-21 14:22 UTC, AilfeLirik commented
![image](https://github.com/user-attachments/assets/4d4b1b76-9b0e-49a4-b9ad-a5a0d15f4ded)
Pour le reflector il y a des points noirs qui me stresent

2024-09-21 14:23 UTC, HARYA301 commented
![image](https://github.com/user-attachments/assets/c6125064-2463-4b8e-a900-b5f73381e40a)

2024-09-21 14:24 UTC, AilfeLirik commented
![image](https://github.com/user-attachments/assets/8659389c-5dd9-401c-91c1-addc3011016c)
Il faut adapter le patern du fond, la tu as mis celui du reflector qui a un centre carré, hors ici on a un centre rond donc il faut changer les formes utilisées

2024-09-21 14:30 UTC, HARYA301 commented
je fais un truc, si ça te plait pas j'arrête pour aujourd'hui

2024-09-21 14:31 UTC, HARYA301 commented
> Fonce un tout petit peu le contour clair sur le haut

montre en screen pour ce genre de truc, merci

2024-09-21 14:45 UTC, HARYA301 commented
J'en ai fait deux @AilfeLirik 
Si t'aimes aucune des deux, et bien tu attendras demain ou lundi prochain
![image](https://github.com/user-attachments/assets/8f8081fb-701e-40e0-8add-693aa6a012c1)

2024-09-21 14:49 UTC, AilfeLirik commented
![image](https://github.com/user-attachments/assets/bc994ed3-0721-4487-95b6-075d327aaaf4)

2024-09-21 14:51 UTC, AilfeLirik commented
L'Alert block de droite est bien, si tu sais m'en fait une vue 3d on devrait être bon

2024-09-21 14:52 UTC, HARYA301 commented
Sache que je te refuse de suite la modification
 Ce que tu suggestifs n'a pas de sens dans le pixel art
La lumière provient du dessus du bloc dans normal que le dessus du bloc soit clair. Par conséquent, les cotés ne peuvent pas être plus claires que le dessus

2024-09-21 14:52 UTC, HARYA301 commented
> L'Alert block de droite est bien, si tu sais m'en fait une vue 3d on devrait être bon

et pour ça okay

2024-09-21 14:55 UTC, HARYA301 commented
rendu 3d
![image](https://github.com/user-attachments/assets/751db5f2-0bbd-4650-a98d-2ebd0928efbc)

2024-09-21 14:59 UTC, AilfeLirik commented
![image](https://github.com/user-attachments/assets/584b33d2-8c78-4e61-a0cf-c3cac7c6ca7a)
Je ne te demande pas de les foncer plus que les autres bord il faut simplement les rendre un peu plus foncé puisqu'ils sont trop clairs par rapport au reste

2024-09-21 15:02 UTC, HARYA301 commented
C'est le max que je te fais.
![image](https://github.com/user-attachments/assets/f9a2818c-1848-48fc-bd84-fac180d1f8b2)

2024-10-19 21:32 UTC, AilfeLirik approved these changes

2024-10-19 21:32 UTC, AilfeLirik commented
A verif par dado et merge

2024-10-19 21:33 UTC, AilfeLirik commented
![image](https://github.com/user-attachments/assets/de4341b7-75d8-43dd-9f74-693408eeb024)

2024-10-20 11:59 UTC, dadodasyra requested changes
Manque les langs ?

2024-10-20 12:03 UTC, HARYA301 commented
Okay

2024-10-20 14:15 UTC, AilfeLirik commented
@dadodasyra tu valides ?

2024-10-20 16:53 UTC, merged