Sticks textures changes
HisteriaMC/HisteriaPack pull request #5
Opened 2023-08-18 19:29 UTC by AilfeLirik

Changement des textures de sticks par Haragon

2023-08-29 20:43 UTC, zelytra commented
Up @AilfeLirik @dadodasyra ?

2023-08-30 13:41 UTC, dadodasyra requested changes
Ce serait cool d'avoir les preview, je ne crois pas que le sponger ai changé et il faut aussi l'avis de @Ichabodt et de @AilfeLirik

2023-08-31 18:40 UTC, Ichabodt requested changes
Globalement j'ai un peu de mal avec ces textures. D'un œil comparatif je trouve les textures d'Edward visuellement plus plaisantes, mais celles d'Harya sont plus claires quant à leurs fonctions, **exception faite du speedstick**.

2023-10-04 06:46 UTC, dadodasyra commented
Le fait que cette PR soit créé par Ailfe et pas par @harya n'aide pas trop..

2023-10-04 15:47 UTC, zelytra commented
on la delete ?

2023-10-09 19:15 UTC, closed without merging