Create fertilized_dirt.png
HisteriaMC/HisteriaPack pull request #6
Opened 2023-08-18 19:43 UTC by HARYA301

2023-08-18 19:44 UTC, dadodasyra requested changes
Il faut que tu supprimes l'ancienne texture.
Il faut les changements dans le block_textures.json (ou flipbook ?) puisque tu changes le chemin

2023-08-29 20:42 UTC, zelytra commented
Pour rappel @HARYA301 pour faire savoir que tu as effectué les changements demandés, il faut résoudre le thread de dado "resolve threads"

2023-08-29 20:43 UTC, HARYA301 commented
> Pour rappel @HARYA301 pour faire savoir que tu as effectué les changements demandés, il faut résoudre le thread de dado "resolve threads"

dans tous les cas je vais close la PR parce que je vais en crée une autre plus spécifique que pour un seul bloc

2023-08-29 20:51 UTC, HARYA301 commented
Je close car https://github.com/HisteriaMC/HisteriaPack/pull/10

2023-08-29 20:51 UTC, closed without merging