Added Fossils
HisteriaMC/HisteriaPack pull request #7
Opened 2023-08-18 20:13 UTC by HARYA301

2023-08-18 20:15 UTC, AilfeLirik approved these changes

2023-08-29 20:42 UTC, HARYA301 commented
Si ça peut être approuvé, merci @dadodasyra ou @Ichabodt

2023-08-30 13:42 UTC, dadodasyra requested changes

2023-08-30 13:45 UTC, HARYA301 commented on textures/items/fossils/stone_pieces_histeria.png
> Quel est cet item, le nom ne me semble pas approprié ? c'est des bouts d'histerite ou.. on sait pas en fait

Le nom n'est pas correcte sans aucune raison. Je vais te fixer ça

2023-08-31 16:55 UTC, AilfeLirik approved these changes

2023-08-31 16:56 UTC, HARYA301 commented
Vous pouvez pas approuvé du coup?
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/f59b4245-9de5-4de5-a596-37d7b76adc6d)

2023-08-31 17:02 UTC, zelytra commented
PR ok, en attente des changements de params de la repo pour merge

2023-08-31 17:11 UTC, merged