Added Customs Blocks
HisteriaMC/HisteriaPack pull request #8
Opened 2023-08-20 13:21 UTC by HARYA301

2023-08-20 15:12 UTC, dadodasyra requested changes
- Tout les noms doivent être en anglais
- Les id de geometry n'ont pas été défini (geometry.unknown)
- Pourquoi les quadrillages s'appellent "black_color_block", pourquoi black et pourquoi block
- Pourquoi un dossier custom_blocks, ça devrait être dans textures/blocks

2023-08-20 15:12 UTC, dadodasyra commented on models/blocks/table.json
.geo.json ?

2023-08-20 15:12 UTC, dadodasyra commented on textures/custom_blocks/peony.png
ça va override la vanilla

2023-08-20 15:20 UTC, HARYA301 commented on models/blocks/table.json
Parce que les .geo sont des .json

2023-08-20 15:20 UTC, HARYA301 commented
> * Tout les noms doivent être en anglais
> * Les id de geometry n'ont pas été défini (geometry.unknown)
> * Pourquoi les quadrillages s'appellent "black_color_block", pourquoi black et pourquoi block
> * Pourquoi un dossier custom_blocks, ça devrait être dans textures/blocks

Je te fix ça ce soir

2023-08-20 15:21 UTC, HARYA301 commented on textures/custom_blocks/peony.png
Je vais sûrement la supprimer en vrai

2023-08-20 15:58 UTC, HARYA301 commented
C'est bon j'ai fait tes modifs

2023-08-20 18:10 UTC, dadodasyra commented on models/blocks/table.json
Nan mais apprend à lire pls. Le nom du fichier

2023-08-20 18:11 UTC, HARYA301 commented on models/blocks/table.json
C'est normal je te dis

2023-08-20 18:11 UTC, dadodasyra commented
Plein d'incohérences. Orange bush et les noms de fichiers. Guirlande qui n'est ni en français ni en anglais.. bref je refais une review sur pc later

2023-08-20 18:11 UTC, HARYA301 commented on models/blocks/table.json
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/acb4c8e8-ca3f-4557-8beb-95ab08386278)

2023-08-20 18:11 UTC, dadodasyra commented on models/blocks/table.json
Donc c'est normal que tu n'as pas mit de .geo.  dans ce nom de fichier

2023-08-20 18:13 UTC, HARYA301 commented on models/blocks/table.json
Je viens de checker et uniquement celui de la table ne le contient pas... merci Blockbench d'avoir niquer mon truc 
Je te refais un commit

2023-08-20 18:14 UTC, dadodasyra commented on models/blocks/table.json
D'où le commentaire qui concerne ce fichier.

2023-08-20 18:15 UTC, HARYA301 commented on models/blocks/table.json
Ah j'avais pas vu que le truc en haut sur Github
NORMALEMNT ça devrait être bon

2023-08-20 18:16 UTC, HARYA301 commented on textures/custom_blocks/peony.png
Changement: ça ne va plus override la texture Vanilla, maintenant c'est "peony_bush" avec une toute nouvelle texture

2023-08-20 19:30 UTC, dadodasyra commented on models/blocks/table.json
Alors il faut que tu le définisses en resolve

2023-08-20 19:39 UTC, dadodasyra requested changes
les modèles de pousses de nocturite sont pas les mêmes entre eux? j'avais dit btw qu'il faut faire nocturite_plant_stage_X
J'ai vu que tu as supprimé certains anciens block, j'aimerai bien que tu les supprimes uniquement si tu les a déjà remplacé avec leur équivalent custom (genre bone_block doit être supprimé si il y a les cave block)
Il manque les reviews d'artiste pour les textures

2023-08-20 19:39 UTC, dadodasyra commented on models/blocks/book.geo.json
ce serait bien d'avoir un autre nom, surtout que, juste "book" ? c'est quoi ? bookshelf ? en fait faudrait pas que ça ai le meme nom qu'un item/block vanilla

2023-08-20 19:39 UTC, dadodasyra commented on textures/blocks/flipbook_textures.json
Plus de neon block ?

2023-08-20 19:39 UTC, dadodasyra commented on textures/blocks/lucky_block.png
J'aimerai bien un haut différent des cotés. et le bas, (comme une table de craft)

2023-08-20 20:28 UTC, HARYA301 commented on textures/blocks/flipbook_textures.json
J'avais oublié qu'il existait

2023-08-20 20:28 UTC, HARYA301 commented on models/blocks/book.geo.json
Je vais le rename en "Book stack"

2023-08-21 07:16 UTC, dadodasyra requested changes
Toujours besoin de review sur les textures @AilfeLirik et @Ichabodt

2023-08-21 07:16 UTC, dadodasyra commented on textures/terrain_texture.json
random ore ?

2023-08-21 07:42 UTC, zelytra commented
Trop d'ajout pour moi c'est un refus de merge.

2023-08-21 07:44 UTC, zelytra commented
Il faut découper cette PR, je compte plus de 60 ajouts.

2023-08-21 07:44 UTC, closed without merging