blocs de déco
HisteriaMC/HisteriaPack pull request #80
Opened 2023-09-24 11:07 UTC by HARYA301

2023-09-24 11:07 UTC, HARYA301 commented
(Priorité basse)

2023-09-24 14:07 UTC, zelytra commented
Ne correspond a aucune tâche, ne seras pas traité avant la fin de la milestone v6.5

2023-10-26 08:04 UTC, zelytra commented
Tache in scope, peut reprendre son développement et son implementation

2023-10-28 15:35 UTC, HARYA301 commented
Grande amélioration apporté à l'étagère et mise à jour de terrain_textures.json, blocks.json et flipbook_textures.json

2023-11-03 21:01 UTC, HARYA301 commented
Merci de ne pas approuvé la PR, celle ci n'est finalement pas finalisé et d'autres blocks customs sont en cours!

2023-11-03 21:03 UTC, dadodasyra requested changes
Il faut des noms unique par blocks (pas shelf1 shelf2 shelf3).
Il faut des rendus pour permettre de review la PR
Les trucs genre la lamp avec plusieeurs états si on veut vrm faire plusieurs états faut donner plusieurs textures, fin genre la texture allumé (se baser sur les nocturite_plant qui utilisent déjà la meme techno)

2023-11-03 21:03 UTC, dadodasyra commented on blocks.json
L'indentation n'est pas la bonne, ça doit etre un baille de tab ou d'espaces

2023-11-03 21:05 UTC, HARYA301 commented
> Il faut des noms unique par blocks (pas shelf1 shelf2 shelf3). Il faut des rendus pour permettre de review la PR Les trucs genre la lamp avec plusieeurs états si on veut vrm faire plusieurs états faut donner plusieurs textures, fin genre la texture allumé (se baser sur les nocturite_plant qui utilisent déjà la meme techno)

Pour le shelf qui a différentes textures c'est tout à fait normal. Afin de ne pas avoir qu'un seul model, j'ai crée plusieurs textures qui ont toutes des éléments différents. J'ai ajouté dans 4 variantes de textures qui seront affiché aléatoirement.

2023-12-02 21:50 UTC, closed without merging

2023-12-09 12:01 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/6226a973-db0d-4d20-9554-753d236e0b2e)

2023-12-09 12:01 UTC, HARYA301 commented
C'est l'un des trucs que j'ai fait mais d'autres arrivent

2023-12-09 15:03 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/67d03527-4afd-4e4a-b793-a983acc28be5)

2023-12-12 19:39 UTC, dadodasyra commented
> ![image](https://private-user-images.githubusercontent.com/57374230/289270037-6226a973-db0d-4d20-9554-753d236e0b2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MTAyNjAsIm5iZiI6MTcwMjQwOTk2MCwicGF0aCI6Ii81NzM3NDIzMC8yODkyNzAwMzctNjIyNmE5NzMtZGIwZC00ZDIwLTk1NTQtNzUzZDIzNmUwYjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE5MzkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNzNmYzk2YTllZWQ2MmFlZDc4NjFhMjdlNjVkY2ExMGI4ZjM3ZmYxYWUyOGE0YWVmZjk0YTBiNjgwYmRjOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ie1xnN1SKkDPjIVE3kf8klWoCQ3U08Dzb4kCx0Txq1c)

c quoi ça

2023-12-12 19:50 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/0d0efca3-0730-4d58-b901-f58b96b70857)

2023-12-12 19:53 UTC, HARYA301 commented
Ah c'est une table de chevet

2023-12-19 19:21 UTC, dadodasyra commented
Cette PR n'est plus out of scope et doit être finie avant janvier @HARYA301

2024-01-10 08:06 UTC, HARYA301 commented
Faut que je reclone toutes les branches donc je vais forcément regarder ça aujourd'hui

2024-01-10 08:16 UTC, dadodasyra commented
> **Faut que je reclone toutes les branches** donc je vais forcément regarder ça aujourd'hui

càd ?

2024-01-10 08:17 UTC, HARYA301 commented
> > **Faut que je reclone toutes les branches** donc je vais forcément regarder ça aujourd'hui
> 
> càd ?

J'ai changé de PC récemment donc je devais remettre GH Desktop ainsi que les repo et tout le bordel

2024-01-10 08:23 UTC, HARYA301 commented on blocks.json
où?

2024-01-10 08:29 UTC, HARYA301 commented
Il ne reste plus que quelques ajustements à faire et la PR sera **à mes yeux** terminée

2024-01-10 08:59 UTC, HARYA301 commented
> Il faut des noms unique par blocks (pas shelf1 shelf2 shelf3). Il faut des rendus pour permettre de review la PR Les trucs genre la lamp avec plusieeurs états si on veut vrm faire plusieurs états faut donner plusieurs textures, fin genre la texture allumé (se baser sur les nocturite_plant qui utilisent déjà la meme techno)

ça c'est fait

2024-01-10 08:59 UTC, HARYA301 commented
Perso j'ai plus rien à faire sur cette PR
Repasse dessus si tu vois des problèmes

2024-01-11 14:31 UTC, dadodasyra commented
On a tout les renders ? en vrai jpense jvais tester ig ce sera plus simple

2024-01-11 14:36 UTC, HARYA301 commented
> On a tout les renders ? en vrai jpense jvais tester ig ce sera plus simple

Oui test ingame

2024-01-30 14:24 UTC, HARYA301 commented
Ou ici?

2024-02-04 11:11 UTC, dadodasyra commented
C'est my bad ça, j'ai pas trop eu le temps de m'en occuper

2024-02-04 11:38 UTC, HARYA301 commented
> C'est my bad ça, j'ai pas trop eu le temps de m'en occuper

Pas de problème, le moindre problème que tu as et chose à redire n’hésites pas

2024-02-20 22:16 UTC, dadodasyra commented
Promis je vais m'en occuper

2024-02-20 22:17 UTC, HARYA301 commented
Pas de problème encore une fois 😂

2024-02-29 12:13 UTC, HARYA301 commented
Alors, qu'est ce que ça donne?😂

2024-03-23 20:05 UTC, HARYA301 commented
Bon bah je demande ici 😂

2024-04-27 20:08 UTC, dadodasyra commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/44753923/ddd7b04b-602e-4632-89c4-5ec7047d2f7f)
La chaise est pas orienté dans le bon sens, il faut la rotate de 90° sens contraire des aiguilles d'une montre

2024-04-27 20:11 UTC, HARYA301 commented
Je fais ça quand je rentre de chez ma mère

2024-04-27 20:31 UTC, dadodasyra commented
Les tiles colorées doivent être dans une liste de texture tel quel : 
![image](https://github.com/HisteriaMC/HisteriaPack/assets/44753923/f127017e-812a-4397-ae33-a2b68a88afc4)
(blocks.json change pas)

2024-04-27 21:01 UTC, dadodasyra commented
Les guirlandes à rotate de 90° aussi, peu importe le sens

2024-05-03 14:05 UTC, HARYA301 commented
> Les tiles colorées doivent être dans une liste de texture tel quel

Mets toi à jour, ce n'est plus du tout comme ça. Mojang laisse ça dans le fichier mais ce n'est plus du tout d'actualité:
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/b5e4b5a1-5efc-4804-b5d6-17574b6a8d81)