Changement textures items (Vague 1)
HisteriaMC/HisteriaPack pull request #81
Opened 2023-09-26 12:20 UTC by HARYA301

2023-09-26 12:21 UTC, HARYA301 commented
Lié à ces 10 issues

![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/917c95a3-2ace-45c4-94e1-edff1a775bf2)

2023-09-26 12:21 UTC, ItamSurMc commented
Tague les issues que tu traites en description. Par exemple pour le hammer : #76

2023-09-26 12:23 UTC, HARYA301 commented
#76 #74 #68 #66 #65 #57 #55 #54 #53

2023-09-27 16:37 UTC, Ichabodt requested changes
Je ne sais vraiment pas quoi penser des compress, je ne suis pas fan, mais en même temps je ne vois pas quoi te dire pour les changer...
Quant aux cores je trouve qu'ils ont un côté "plastique" ou caoutchouteux.

2023-09-27 16:37 UTC, Ichabodt commented on textures/items/hammer.png
Je vais y aller cash, je n'aime pas cette texture, je préfère clairement l'ancienne !

2023-09-27 16:37 UTC, Ichabodt commented on textures/items/histerite_apple.png
En soi c'est correct, mais il faudrait trouver un moyen de la distinguer plus clairement de la pomme vanilla. Peut-être reprendre l'idée des reflets de l'autre texture ?

2023-09-27 16:37 UTC, Ichabodt commented on textures/items/lottery_ticket.png
Je ne sais pas s'il t'a été demandé d'ajouter ce H, mais je ne pense pas qu'il soit nécessaire. Pour moi on peut rester sur l'ancienne texture.

2023-09-27 16:39 UTC, HARYA301 commented on textures/items/histerite_apple.png
Elle est déjà très bien distinguer déjà je pense de la vanilla.
Si je rajoute des reflets ça rendra la texture moins bien car trop clair.

2023-09-27 16:40 UTC, HARYA301 commented on textures/items/lottery_ticket.png
Demande par Ailfe. Si la texture est dans la liste des issues, alors je suis dans l'obligation de la changer.

2023-09-27 16:49 UTC, Ichabodt commented on textures/items/histerite_apple.png
Si tu as les deux sous les yeux oui. Mais si tu vois l'item à terre je pense que tu peux les confondre assez aisément. Un peu comme certains joueurs ont du mal à distinguer l'histerite de la redstone en minant !
Si les reflets ne te conviennent pas, pas de soucis c'est juste une proposition. Mais je pense qu'il faut trouver un truc !

2023-09-27 16:49 UTC, HARYA301 commented on textures/items/hammer.png
> Peut être simplement modifier la forme de celui d'edward

Oui mais avec des changements tout de même. 
La texture correspond mal à la DA de MC.

2023-09-27 16:50 UTC, AilfeLirik commented on textures/items/hammer.png
essaie de virer quelques petites pixels dans les coins du hammer d'eward pour l'arrondir juste un petit peu

2023-09-27 16:50 UTC, AilfeLirik commented on textures/items/histerite_apple.png
Faut accentuer qlq chose on la confond je suis d'accord

2023-09-27 16:54 UTC, AilfeLirik commented on textures/items/histerite_apple.png
@dadodasyra need your opinion

2023-09-27 16:55 UTC, HARYA301 commented on textures/items/histerite_apple.png
@AilfeLirik Elle donne quoi comme effet la pomme?

2023-09-27 16:56 UTC, AilfeLirik commented on textures/items/histerite_apple.png
![image](https://github.com/HisteriaMC/HisteriaPack/assets/95536716/55f6db62-465a-451f-960e-0133a7859040)

2023-09-27 16:57 UTC, Ichabodt commented on textures/items/histerite_apple.png
Pour la confusion avec la redstone, le minerai d'histerite a complètement été refait, tu le sais, tu es toi-même repassé sur la texture. Et là on a le même problème, deux pommes qui ont la même forme et la même couleur, confusion à prévoir assurément !

2023-09-27 16:57 UTC, HARYA301 commented on textures/items/histerite_apple.png
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/ee65ae7e-67ab-49bf-83f4-ca75f978ded4)

2023-09-27 16:59 UTC, HARYA301 commented on textures/items/histerite_apple.png
> Pour la confusion avec la redstone, le minerai d'histerite a complètement été refait, tu le sais, tu es toi-même repassé sur la texture. Et là on a le même problème, deux pommes qui ont la même forme et la même couleur, confusion à prévoir assurément !

Après sur un serveur PvP les gens vont se dire que c'est une pomme Vanilla car je pense que personne n'utilise la vanilla sur le serveur mise à part pour la craft

2023-09-27 16:59 UTC, AilfeLirik commented on textures/items/histerite_apple.png
Nan par contre c'est un item de pvp on ne peut vraiment pas se permettre de rajouter des pixels qui flottent autour, désolé

2023-09-27 16:59 UTC, HARYA301 commented on textures/items/histerite_apple.png
J'ai fait une nouvelle version, dites moi votre impression

2023-09-27 18:56 UTC, dadodasyra commented on textures/items/histerite_apple.png
efffectivement ça cxolle trop à celle vanilla

2023-09-27 18:56 UTC, dadodasyra commented on textures/items/lottery_ticket.png
j'aime bien l'aspect des bords gauche et droite qui sont "mordu" type réel ticket. L'ancienne texture ressemble plus à un badge qu'autre chose, mais le H effectivement c'est pas ouf

2023-09-27 18:57 UTC, HARYA301 commented on textures/items/lottery_ticket.png
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/bcd30e9f-4b49-4572-854c-766d69af3042)

2023-09-27 21:50 UTC, dadodasyra commented on textures/items/lottery_ticket.png
Pour moi c'est ok

2023-09-29 17:48 UTC, HARYA301 commented on textures/items/hammer.png
Maintenant ça donne quoi?

2023-10-04 06:43 UTC, dadodasyra reviewed
Avis de @AilfeLirik @Ichabodt qui prime

2023-10-04 15:18 UTC, AilfeLirik commented on textures/items/histerite_apple.png
ducoup change

2023-10-06 18:13 UTC, HARYA301 commented on textures/items/hammer.png
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/3e12c421-a205-4585-b7b7-4408ca14a221)

2023-10-09 19:09 UTC, zelytra commented
@HARYA301 des news sur les thread non resolve ? continue de les commenté pour avois une update

2023-10-09 19:11 UTC, Ichabodt commented on textures/items/hammer.png
@AilfeLirik je sais que le manche rouge correspond au craft, mais perso je ne suis pas fan du mélange de couleur. Donc si toi tu aimes comme ça, on part là-dessus, mais je préfère toujours l'ancien

2023-10-09 19:13 UTC, Ichabodt requested changes
J'attends l'avis d'Ailfe pour le hammer. Quant à la pomme, je maintiens qu'il faut la différencier de la vanilla

2023-10-09 19:42 UTC, HARYA301 commented
> J'attends l'avis d'Ailfe pour le hammer. Quant à la pomme, je maintiens qu'il faut la différencier de la vanilla

Je peux rien faire d'autre pour la pomme.

2023-10-09 20:39 UTC, zelytra commented
Je t'invite de nouveaux a relire, au prochain message je la repasse en invalide

2023-10-10 17:20 UTC, AilfeLirik commented on textures/items/hammer.png
Effectivement mélange de couleur est pas génial, il faut tenter autre chose

2023-10-10 17:21 UTC, AilfeLirik commented
Hammer à edit, sinon j'abandonne pour la pomme, ça fera le taff

2023-10-10 17:22 UTC, HARYA301 commented
Elle sera toujours mieux que l'actuelle

2023-10-10 17:24 UTC, HARYA301 commented on textures/items/hammer.png
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/0b2d2ada-853c-44c4-8424-77e416a6e9e9)

2023-10-10 17:26 UTC, HARYA301 commented on textures/items/hammer.png
Pour info j'ai repris les anciennes couleurs pour le stick

2023-10-10 17:27 UTC, HARYA301 commented
@Ichabodt Je ne veux pas ne pas changer la pomme mais vu que la date butoir est samedi, j'ai VRAIMENT très peu de temps, genre très très très peu

2023-10-10 17:35 UTC, HARYA301 commented
Oui je comprends et en aucun cas je rejette tes feedbacks. Juste que là je ne sais pas quoi en faire et Ailfe a give up pour la pomme. Je peux essayer une dernière fois mais bon, ça risque de ne rien arranger

2023-10-11 15:33 UTC, AilfeLirik commented
Je valide le nv hammer

2023-10-11 16:36 UTC, zelytra commented
@Ichabodt

2023-10-11 16:58 UTC, Ichabodt approved these changes
Foncièrement je n'ai rien à dire de plus que je n'ai déjà dit. @dadodasyra à toi de trancher !

2023-10-11 17:02 UTC, merged