Items (Phase 2)
HisteriaMC/HisteriaPack pull request #87
Opened 2023-10-11 18:26 UTC by HARYA301

2023-10-11 18:30 UTC, HARYA301 commented
#77 #78 #59 #75 #73 #69 #67 #64 #63 #71

2023-10-11 19:11 UTC, dadodasyra requested changes

2023-10-11 19:11 UTC, dadodasyra commented on textures/items/forge_note.png
pas sur que ça ai été approuvé par ailfe ça

2023-10-11 19:11 UTC, dadodasyra commented on textures/items/nether_wart.png
nom du fichier faux

2023-10-11 19:14 UTC, HARYA301 commented on textures/items/nether_wart.png
c'est bon c'est fait

2023-10-11 19:16 UTC, HARYA301 commented on textures/items/forge_note.png
La raison pourquoi la texture est vachement différente est que l'actuelle reprend juste le "banner pattern", ce qui n'a pas de sens
Si vous voulez que je le change, okay

2023-10-13 18:59 UTC, AilfeLirik commented on textures/items/forge_note.png
C'est ok on prends ça

2023-10-13 18:59 UTC, AilfeLirik approved these changes

2023-10-13 19:02 UTC, dadodasyra approved these changes

2023-10-13 19:02 UTC, dadodasyra commented on textures/items/nocturite_crystal.png
c'est vraiment cool ça en vrai

2023-10-13 19:02 UTC, dadodasyra commented
@zelytra on peut skip icha sur celle là

2023-10-13 19:07 UTC, merged