Items (Vague 4)
HisteriaMC/HisteriaPack pull request #92
Opened 2023-10-13 18:50 UTC by HARYA301

2023-10-13 18:53 UTC, HARYA301 commented
#70 #52 #51 #50 #49 #48 #47 #46 #45 #42

2023-10-13 18:56 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/12912391-b97b-4dce-bc39-99f66383fb0c)
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/426b9318-e1ab-455f-93c2-8a6a0ffc3457)

2023-10-13 18:57 UTC, dadodasyra requested changes

2023-10-13 18:57 UTC, dadodasyra commented on textures/items/histerite_core.png
bof un peu plastique, casiment sur que ça passera pas chez icha

2023-10-13 18:57 UTC, dadodasyra commented on textures/items/obsidian_breaker.png
je vois aucun interet à ça, tu l'as plastifié et simplifié c'est tout

2023-10-13 19:16 UTC, HARYA301 commented on textures/items/histerite_core.png
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/9bd62073-4a54-4e1e-a3cc-bc7199168691)

2023-10-13 19:33 UTC, Ichabodt requested changes

2023-10-13 19:33 UTC, Ichabodt commented on textures/items/dynamite.png
Je sais pas si l'impression est partagé, mais on dirait un extincteur à mes yeux

2023-10-13 19:33 UTC, Ichabodt commented on textures/items/histerite_core.png
Il était pas déjà dans la PR vague 1 lui ?

2023-10-13 19:33 UTC, Ichabodt commented on textures/items/lotus_staff.png
Si je devais dire un truc ici, c'est que les branches sont plus écartées sur l'item que sur le modèle

2023-10-13 19:33 UTC, Ichabodt commented on textures/items/obsidian_breaker.png
Pas fan non plus, pour ma part j'ai plus l'impression qu'il est fait en une sorte de terre ?!

2023-10-13 19:35 UTC, HARYA301 commented on textures/items/histerite_core.png
Je viens de le remarquer que oui

2023-10-13 19:35 UTC, Ichabodt commented
Pour le modèle de la lance @HARYA301, le pic mériterait peut-être d'être plus pointu, autrement c'est sympa !

2023-10-13 19:35 UTC, dadodasyra commented on textures/items/dynamite.png
J'y avais pas pensé mais ça me choque pas

2023-10-13 19:36 UTC, HARYA301 commented
> Pour le modèle de la lance @HARYA301, le pic mériterait peut-être d'être plus pointu, autrement c'est sympa !

C'est normal qu'il soit pas trop pointu, je garde la coté vanilla friendly

2023-10-17 14:30 UTC, HARYA301 commented
Je peux rien faire avec celle là hein

2023-10-17 14:51 UTC, HARYA301 commented on textures/items/dynamite.png
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/32d71711-5dfd-4aee-8e15-451408a817b8)

2023-10-17 14:52 UTC, HARYA301 commented on textures/items/lotus_staff.png
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/b30504e6-3a81-41ef-9e22-fff82b8b2c8a)

2023-10-17 14:53 UTC, HARYA301 commented
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/436474ab-26e8-4d1e-b42b-50415f7b01d0)

2023-10-17 16:43 UTC, Ichabodt commented on textures/items/dynamite.png
Ça me va niquel ça

2023-10-17 16:44 UTC, Ichabodt commented on textures/items/lotus_staff.png
J'avoue que je vois pas le changement là. Cela dit c'était un retour mineur, donc si ça reste comme ça c'est ok

2023-10-17 16:47 UTC, Ichabodt commented
> ![image](https://user-images.githubusercontent.com/57374230/275876816-436474ab-26e8-4d1e-b42b-50415f7b01d0.png)

Je sais pas, je reste mitigé, à voir ce que @dadodasyra en pense, il avait déjà l'air d'avoir un avis plus tranché sur la question

2023-10-17 16:48 UTC, HARYA301 commented
Okay. C'est la forme qui te dérange le plus?

2023-10-17 17:01 UTC, Ichabodt commented
Le choix des couleurs/des tons plutôt. L'objet est terne, un peu comme de la pierre, le matériau n'a pas l'air assez solide pour briser de l'obsidienne.
Et le manche violet, pas super fan non plus, mais après ça c'est une question goût.

2023-10-17 17:02 UTC, HARYA301 commented
> Le choix des couleurs/des tons plutôt. L'objet est terne, un peu comme de la pierre, le matériau n'a pas l'air assez solide pour briser de l'obsidienne. Et le manche violet, pas super fan non plus, mais après ça c'est une question goût.

Je comprends. Je vais voir ça et je te redis. Pour les couleurs ça se tient mais je vais essayer de trouver la bonne balance

2023-10-18 11:40 UTC, dadodasyra requested changes

2023-10-18 11:40 UTC, dadodasyra commented on textures/items/dynamite.png
manque l'entité custom liée à ça, avec son render, id d'entité histeria:dynamite

2023-10-18 11:40 UTC, dadodasyra commented on textures/items/obsidian_breaker.png
je réitère. je pense pas qu'on doit changer ça

2023-10-18 11:42 UTC, HARYA301 commented
Alors que je voudrais tu que je fasse? Ailfe m'a demandé de le faire, je fais...

2023-10-18 11:47 UTC, HARYA301 commented
> Le choix des couleurs/des tons plutôt. L'objet est terne, un peu comme de la pierre, le matériau n'a pas l'air assez solide pour briser de l'obsidienne. Et le manche violet, pas super fan non plus, mais après ça c'est une question goût.

![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/ccb9453d-064d-415a-ba15-852c89ea55e5)
@Ichabodt

2023-10-18 14:47 UTC, Ichabodt commented
J'aime mieux ! D'ailleurs @HARYA301 t'attardes pas plus sur l'obsidian breaker, Ailfe veut faire quelque chose avec l'item, mais il ne sait pas quoi

2023-10-18 14:56 UTC, zelytra commented
L'issue ne prend plus en charge l'obsi breaker, merci de la supprimer des changement de la pr

2023-10-18 15:04 UTC, HARYA301 commented
Je la supprime de la PR mais ça va aussi la supprimer de la branche V6.5 si la PR est approuvé non?

2023-10-18 15:38 UTC, Ichabodt approved these changes

2023-10-18 16:22 UTC, dadodasyra approved these changes

2023-10-21 10:33 UTC, HARYA301 commented on textures/items/dynamite.png
Pas le temps pour le model 3D avec l'anim
On resolve la conv?

2023-10-21 10:36 UTC, dadodasyra commented on textures/items/dynamite.png
Minimum l'entité, pas besoin forcément de l'animation alors

2023-10-21 10:36 UTC, dadodasyra commented on textures/models/armor/hood_helmet_1.png
normal le titre du fichier? volontaire ?

2023-10-21 10:37 UTC, HARYA301 commented on textures/models/armor/hood_helmet_1.png
Oui

2023-10-21 10:46 UTC, HARYA301 commented on textures/items/dynamite.png
C'est fait

2023-10-21 10:46 UTC, HARYA301 commented on textures/items/dynamite.png
![image](https://github.com/HisteriaMC/HisteriaPack/assets/57374230/1745f903-a257-43b4-94c5-06932a7368d8)

2023-10-21 13:29 UTC, dadodasyra commented on models/entity/dynamite.geo.json
> +				"identifier": "geometry.histeria.dynamite",
vanilla c'est minecraft.dynamite ? je sais vrm pas cque je dois mettre moi je choisi pas d'id de geometry

2023-10-21 14:20 UTC, HARYA301 commented on models/entity/dynamite.geo.json
> +				"identifier": "geometry.histeria.dynamite",
corrigé, j'ai juste mis "geometry.dynamite"

2023-10-21 14:20 UTC, HARYA301 commented
vous pouvez merde maintenant

2023-10-21 14:21 UTC, ItamSurMc commented
merde ou merge @HARYA301 ? xD

2023-10-21 14:21 UTC, dadodasyra approved these changes

2023-10-21 14:24 UTC, merged